name: TromLogin
version: '${project.version}'
main: me.generalt.tromlogin.TromLogin
api-version: '1.19'

permissions:
  'tromlogin.broadcast':
    description: 'Broadcasts the join/quit messages'
    default: false
  'tromlogin.bypass':
    description: Bypasses welcome message.
    default: op

commands:
  tromlogin:
    aliases: tl
    permission-message: "&cYou do not have permission to run this command, bozo."
    reload:
      description: Reloads the plugin configuration
      permission: tromlogin.reload
    test:
      description: Tests the messages.
      permission: tromlogin.test